[versions]
# libraries
junit = "5.11.3"
junit4 = "4.13.2"
mcpKotlinSdk = "0.8.1"

# plugins
changelog = "2.4.0"
intelliJPlatform = "2.10.4"
kotlin = "2.2.21"
kover = "0.9.3"
qodana = "2025.2.2"

[libraries]
mcpKotlinSdkClientJvm = { group = "io.modelcontextprotocol", name = "kotlin-sdk-client-jvm", version.ref = "mcpKotlinSdk" }
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit" }
junit-jupiter-params = { group = "org.junit.jupiter", name = "junit-jupiter-params", version.ref = "junit" }
junit-platform-launcher = { group = "org.junit.platform", name = "junit-platform-launcher" }
junit-vintage-engine = { group = "org.junit.vintage", name = "junit-vintage-engine", version.ref = "junit" }
junit4 = { group = "junit", name = "junit", version.ref = "junit4" }

[plugins]
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
intelliJPlatform = { id = "org.jetbrains.intellij.platform", version.ref = "intelliJPlatform" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
qodana = { id = "org.jetbrains.qodana", version.ref = "qodana" }

[bundles]
junit = ["junit-jupiter", "junit-jupiter-params"]
