[versions]
# libraries
junit = "5.14.1"
junitPlatform = "1.14.1"
opentest4j = "1.3.0"
kotlinxCoroutines = "1.10.2"
kotlinxSerialization = "1.9.0"
mockk = "1.14.6"

# plugins
changelog = "2.4.0"
intelliJPlatform = "2.10.4"
kotlin = "2.2.21"
kotlinSerialization = "2.2.21"
kover = "0.9.3"
qodana = "2025.2.2"

[libraries]
junit = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit" }
junit-platform-launcher = { group = "org.junit.platform", name = "junit-platform-launcher", version.ref = "junitPlatform" }
opentest4j = { group = "org.opentest4j", name = "opentest4j", version.ref = "opentest4j" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerialization" }
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }

[plugins]
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
intelliJPlatform = { id = "org.jetbrains.intellij.platform", version.ref = "intelliJPlatform" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlinSerialization" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
qodana = { id = "org.jetbrains.qodana", version.ref = "qodana" }
